In [23]:
from corm import model
import os
import numpy as np
import pandas as pd

In [30]:
os.chdir('/Users/Erin/git/diablo_data/corm_sensitivity/')
np_params = np.load('CORM_MCMCtest_onlypost_rate_parameters_om_log.npy')
np_yout = np.load('CORM_MCMCtest_onlypost_yout_om_log.npy')
np_inits = np.load('CORM_MCMCtest_onlypost_initial_parameters_om_log.npy')

IOError: [Errno 2] No such file or directory: 'CORM_MCMCtest_onlypost_rate_parameters_om_log.npy'

In [25]:
np_yout.shape

(588000, 100)

In [26]:
np_inits[96000]

array([ 0.015,  0.5  ,  0.5  ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ])

In [27]:
np_params[96000]

array([  1.50000000e-02,   5.00000000e-01,   5.00000000e-01,
         0.00000000e+00,   0.00000000e+00,   1.50000000e+04,
         8.30000000e+02,   1.30000000e+00,   1.50000000e+04,
         7.26255429e+00,   1.38519272e+01,   1.50000000e+04,
         2.45044501e-04,   4.19641430e-01,   1.50000000e+04,
         7.60000000e+02,   1.20000000e+00,   1.50000000e+04,
         7.55443476e+02,   1.50000000e+04,   6.97983597e+02,
         3.73287682e+00,   1.50000000e+04,   3.65784250e+01,
         1.50000000e+04,   3.91086540e-01,   1.50000000e+04,
         2.13528809e-02,   1.50000000e+04,   4.40318226e-01,
         1.50000000e+04,   3.29139887e-03,   1.50000000e+04,
         6.30000000e+04])

In [29]:
np_yout['__s1']

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])